### PR TITLE
Add a banner to ask for cookie consent (opt-in) from the user

### PR DESCRIPTION
**Pull request by DilumAluthge**
This pull request adds a banner that asks the user for cookie consent (opt-in).

It uses: https://github.com/Alex-D/Cookies-EU-banner

Please note: this pull request does not add Google Analytics or any other kind of analytics. It simply adds the opt-in cookie consent banner.

---

See also: https://github.com/Alex-D/Cookies-EU-banner/blob/master/README.md#in-your-pages

### CODE REVIEW

**Comment by aeisman** [comment]
Preview not working

**Comment by DilumAluthge** [comment]
Yeah I broke the build while trying to add a feature.

**Comment by DilumAluthge** [comment]
Unclear what I have done. Let's try a new PR.

**Comment by DilumAluthge** [comment]
Closing in favor of #100

**Pull request closed without merging**
