### PR TITLE
Add a banner to ask for cookie consent (opt-in) from the user

### PR DESCRIPTION
**Pull request by DilumAluthge**
Closes #96 

---

This pull request adds a banner that asks the user for cookie consent (opt-in).

It uses: https://github.com/Alex-D/Cookies-EU-banner

Please note: this pull request does not add Google Analytics or any other kind of analytics. It simply adds the opt-in cookie consent banner.

---

See also: https://github.com/Alex-D/Cookies-EU-banner/blob/master/README.md#in-your-pages

### CODE REVIEW

**Comment by DilumAluthge** [comment]
For some reason it's being buggy. If you click reject, the banner goes away, and GA is disabled.

If you click accept, GA is enabled, but for some reason the banner keeps appearing on every subsequent page, even though you already clicked accept.

**Comment by DilumAluthge** [comment]
The preview should be working now. @aeisman

**Comment by DilumAluthge** [comment]
Okay, everything is finally working now, including the "revoke consent" feature.

**Comment by aeisman** [comment]
Please hold off on merging this

**Comment by DilumAluthge** [comment]
From triage: put this on hold until we have consulted with some other departments.

**Pull request closed without merging**
